repositories:
  # Local bootstrap files in this repo.
  bootstrap:
    type: plugin
    source_dir: ./bootstrap/plugins

  # https://github.com/squizlabs/PHP_CodeSniffer
  phpcbf-github:
    type: tool-github
    repository: squizlabs/PHP_CodeSniffer
    tool-name: phpcbf
    allowed-versions: ^3.0 || ^2.0

  # https://github.com/squizlabs/PHP_CodeSniffer
  phpcs-github:
    type: tool-github
    repository: squizlabs/PHP_CodeSniffer
    tool-name: phpcs
    allowed-versions: ^3.0 || ^2.0

  # https://github.com/phpmd/phpmd
  # https://phpmd.org
  phpmd-github:
    type: tool-github
    repository: phpmd/phpmd
    tool-name: phpmd
    allowed-versions: ^2.6.1

  plugin-github:
    type: plugin-github
    repositories:
      - phpcq/plugin-box
      - phpcq/plugin-composer-normalize
      - phpcq/plugin-composer-require-checker
      - phpcq/plugin-phpcpd
      - phpcq/plugin-phploc
      - phpcq/plugin-phpunit
      - phpcq/plugin-psalm
