repositories:
  # Local bootstrap files in this repo.
  bootstrap:
    type: plugin
    source_dir: ./bootstrap/plugins

  plugin-github:
    type: plugin-github
    repositories:
      - phpcq/plugin-box
      - phpcq/plugin-composer-normalize
      - phpcq/plugin-composer-require-checker
      - phpcq/plugin-phpcpd
      - phpcq/plugin-phpcs
      - phpcq/plugin-phploc
      - phpcq/plugin-phpmd
      - phpcq/plugin-phpunit
      - phpcq/plugin-psalm
