repositories:
  # static overrides for various tool releases which are incorrect in upstream.
  overrides:
    type: tool-static
    tools:
      psalm:
        - version: 6.9.0
          requirements:
            php:
              php: ~8.2.27 || ~8.3.16 || ~8.4.3
        - version: 6.9.2
          requirements:
            php:
              php: ~8.2.27 || ~8.3.16 || ~8.4.3
        - version: 6.9.3
          requirements:
            php:
              php: ~8.2.27 || ~8.3.16 || ~8.4.3
        - version: 6.9.4
          requirements:
            php:
              php: ~8.2.27 || ~8.3.16 || ~8.4.3
        - version: 6.9.5
          requirements:
            php:
              php: ~8.2.27 || ~8.3.16 || ~8.4.3
        - version: 6.9.6
          requirements:
            php:
              php: ~8.2.27 || ~8.3.16 || ~8.4.3
        - version: 6.10.0
          requirements:
            php:
              php: ~8.2.27 || ~8.3.16 || ~8.4.3
        - version: 6.10.1
          requirements:
            php:
              php: ~8.2.27 || ~8.3.16 || ~8.4.3
        - version: 6.10.2
          requirements:
            php:
              php: ~8.2.27 || ~8.3.16 || ~8.4.3
        - version: 6.10.3
          requirements:
            php:
              php: ~8.2.27 || ~8.3.16 || ~8.4.3
        - version: 6.11.0
          requirements:
            php:
              php: ~8.2.27 || ~8.3.16 || ~8.4.3
            composer:
        - version: 6.12.0
          requirements:
            php:
              php: ~8.2.27 || ~8.3.16 || ~8.4.3
        - version: 6.12.1
          requirements:
            php:
              php: ~8.2.27 || ~8.3.16 || ~8.4.3

  plugin-github:
    type: plugin-github
    repositories:
      - phpcq/plugin-box
      - phpcq/plugin-composer-normalize
      - phpcq/plugin-composer-require-checker
      - phpcq/plugin-phpcpd
      - phpcq/plugin-phpcs
      - phpcq/plugin-phploc
      - phpcq/plugin-phpmd
      - phpcq/plugin-phpunit
      - phpcq/plugin-psalm
      - phpcq/plugin-deptrac
      - phpcq/plugin-rector
      - phpcq/plugin-doctrine-coding-standard
