repositories:
  # Local bootstrap files in this repo.
  bootstrap:
    type: plugin
    source_dir: ./bootstrap/plugins

  # https://github.com/maglnet/ComposerRequireChecker
  composer-require-checker-github:
    type: tool-github
    repository: maglnet/ComposerRequireChecker
    tool-name: composer-require-checker
    allowed-versions: ^3.0 | ^2.0

  # https://github.com/squizlabs/PHP_CodeSniffer
  phpcbf-github:
    type: tool-github
    repository: squizlabs/PHP_CodeSniffer
    tool-name: phpcbf
    allowed-versions: ^3.0 || ^2.0

  # https://github.com/squizlabs/PHP_CodeSniffer
  phpcs-github:
    type: tool-github
    repository: squizlabs/PHP_CodeSniffer
    tool-name: phpcs
    allowed-versions: ^3.0 || ^2.0

  # https://github.com/phpmd/phpmd
  # https://phpmd.org
  phpmd-github:
    type: tool-github
    repository: phpmd/phpmd
    tool-name: phpmd
    allowed-versions: ^2.6.1

  # https://github.com/sebastianbergmann/phpunit
  # https://phpunit.de/
  phpunit-github:
    type: tool-github
    repository: sebastianbergmann/phpunit
    tool-name: phpunit
    allowed-versions: ^6.0 || ^7.0 || ^8.0 || ^9.0
  # This provides phpunit, phpcpd, phploc and other tools by Sebastian Bergmann.
  phar.phpunit.de:
    type: tool-phar.io
    url: https://phar.phpunit.de/phive.xml
    tool-name: phpunit
    allowed-versions: ^6.0 || ^7.0 || ^8.0 || ^9.0

  # https://github.com/vimeo/psalm
  # https://psalm.dev/
  psalm-github:
    type: tool-github
    repository: vimeo/psalm
    tool-name: psalm
    allowed-versions: ^3.0 || ^4.0

  plugin-github:
    type: plugin-github
    repositories:
      - phpcq/plugin-box
      - phpcq/plugin-composer-normalize
      - phpcq/plugin-phpcpd
      - phpcq/plugin-phploc
