name: Rebuild repository

env:
  TARGET_BRANCH: gh-pages-test
  TARGET_DIRECTORY: './dir'
  BUILDER_DIRECTORY: './builder'

on:
  # FIXME: Change to master since ready
  push:
    branches:
      - 'feature/github-action'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Pull source
        uses: actions/checkout@v2

      - name: Install repository-builder
        uses: actions/checkout@v2
        with:
          repository: 'phpcq/repository-builder'
          path: ${{ env.BUILDER_DIRECTORY }}

      - name: Cache vendor directory of repository-builder
        uses: actions/cache@v1
        env:
          cache-name: repository-builder-vendor
        with:
          path: ${{ env.BUILDER_DIRECTORY }}/vendor
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Cache var directory of repository-builder
        uses: actions/cache@v1
        env:
          cache-name: repository-builder-var
        with:
          path: ${{ env.BUILDER_DIRECTORY }}/var
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: composer install
        working-directory: ${{ env.BUILDER_DIRECTORY }}

      - name: Checkout target directory
        uses: actions/checkout@v2
        with:
          ref: ${{ env.TARGET_BRANCH }}
          path: ${{ env.TARGET_DIRECTORY }}

      - name: Rebuild repository
        run: ${{ env.BUILDER_DIRECTORY }}/bin/console phpcq:rebuild'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        working-directory: ${{ env.TARGET_DIRECTORY }}
        run: |
          git add repository.json
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update repository after pushing changes"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.TARGET_BRANCH }}
          directory: ${{ env.TARGET_DIRECTORY }}
